version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=flaskblog.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: >
      sh -c "flask run --host=0.0.0.0"
    